export interface InvoiceRequest {
    doNo: string;
}

export interface ProformaInvoiceDTO {
    proformaInvoiceHeaderDTO: ProformaInvoiceHeaderDTO;
    proformaInvoiceDetailDTOList: Array<ProformaInvoiceDetailDTO>;
}

export interface ProformaInvoiceHeaderDTO {
    id: number;
    plant: string;
    doNo: string;
    orderDate: string;
    delDate: string;
    customerCode: string;
    customerName: string;
    contactNumber: string;
    address: string;
    addressTwo: string;
    addressThree: string;
    shippingId: string;
    shippingCustomer: string;
    deliveryDate: string;
    paymentStatus: string;
    shippingCost: number;
    paymentType: string;
    orderStatus: string;
    discount: number;
    totalPrice: number;
    taxId: number;
    shipContactName: string;
    shipDesignation: string;
    shipWorkPhone: string;
    shipHpNo: string;
    shipEmail: string;
    shipCountry: string;
    shipAddr1: string;
    shipAddr2: string;
    shipAddr3: string;
    shipAddr4: string;
    shipState: string;
    shipZip: string;
}

export interface ProformaInvoiceDetailDTO {
    id: number;
    doNo: string;
    doLineNo: number;
    pickStatus: string;
    lineStatus: string;
    item: string;
    itemDescription: string;
    ecomUnitPrice: number;
    quantityOr: number;
    estimateNo: string;
    estimateLineNo: number;
    productGst: number;
    accountName: string;
    taxType: string;
    discount: number;
    discountType: string;
    addOnAmount: number;
    addOnType: string;
    unitCost: number;
    gst: number;
    igst: number;
    cgst: number;
    sgst: number;
    cess: number;
    gstAmount: number;
    igstAmount: number; 
    cgstAmount: number;
    sgstAmount: number; 
    cessAmount: number;
    taxTotalAmount: number;
    taxableAmount: number;
}

export interface InvoiceDTO {
    invoiceHeaderDTO: InvoiceHeaderDTO;
    invoiceDetailDTOList: Array<InvoiceDetailDTO> 
}

export interface InvoiceHeaderDTO {
    id: number;
    customerNo: string;
    invoice: string;
    doNo: string;
    invoiceDate: string;
    dueDate: string;
    paymentTerms: string;
    employeeNo: string;
    itemRates: number; 
    discount: number;
    discountType: string;
    discountAccount: string;
    shippingCost: number;
    adjustment: number;
    subTotal: number;
    totalAmount: number;
    billStatus: string;
    note: string;
    termsAndConditions: string;
    isExpense: number; 
    salesLocation: string;
    advanceFrom: string;
    taxTreatment: string;
    creditNotesStatus: number; 
    taxAmount: number;
    taxStatus: string;
    giNo: string;
    orderDiscount: number;
    incoTerms: string;
    currencyId: string;
    currencyToBase: number;
    shippingId: string;
    shippingCustomer: string;
    origin: string;
    deductInv: number; 
    projectId: number;
    currencyUseQt: number;
    orderDiscountType: string;
    taxId: number; 
    isDiscountTax: number; 
    isOrderDiscountTax: number; 
    isShippingTax: number; 
    outboudGst: number;
    jobNumber: string;
    transportId: number;
    totalPaying: number;
    orderType: string;
    shipContactName: string;
    shipDesgination: string;
    shipWorkPhone: string;
    shipHpNo: string;
    shipEmail: string;
    shipCountry: string;
    shipAddress1: string;
    shipAddress2: string;
    shipAddress3: string;
    shipAddress4: string;
    shipState: string;
    shipZip: string;
    deliveryPerson: string;
    deliveryPersonEmail: string;
    deliveryDate: string;
    peppolDocId: string;
    peppolStatus: number; 
    taxType: number; 
    stateCode: number;
    shipStateCode: number;
    shippingTax: number;
    eInvoiceIRNNo: string;
    eInvoiceAckNo: string;
    eInvoiceEwbNo: string;
    eInvoiceAckDate: string;
    eInvoiceEwbDate: string;
    eInvoiceQr: string;
    paymentType: string;
    viewPrd: number; 
    viewUom: number; 
    viewLoc: number; 
    viewBatch: number; 
    viewQty: number; 
    viewPrice: number; 
    viewDiscount: number; 
    viewTaxable: number; 
    viewGst: number; 
    viewCess: number; 
    viewAmount: number; 
    reference: string;
    viewPriceDiscount: number; 
    viewDiscount1: number; 
    eWayBillNo: string;
    buyerPoNO: string;
    buyerPoDate: string;
    loadDate: string;
    containerNo: string;
    sealNo: string;
}


export interface InvoiceDetailDTO {
    id: number;
    lnNo: number;
    invoiceHdrId: number;
    item: string;
    itemDescription: string;
    accountName: string;
    qty: number;              
    unitPrice: number;        
    ecomUnitPrice: number;        
    discount: number;         
    taxType: string;
    amount: number;           
    discountType: string;
    note: string;
    currencyToBase: number;   
    baseToOrderCurrency: number; 
    loc: string;
    batch: string;
    uom: string;
    packingList: string;
    currencyUseQt: number;    
    isCOGSSet: string;      
    creditNoteQty: number;    
    billOfEntry: string;
    addOnAmount: number;      
    addOnType: number;        
    unitCost: number;         
    gst: number;              
    igst: number;             
    cgst: number;             
    sgst: number;             
    cess: number;             
    gstAmount: number;        
    igstAmount: number;       
    cgstAmount: number;       
    sgstAmount: number;       
    cessAmount: number;       
    taxTotalAmount: number;   
    mrp: number;              
    sellingPrice: number;     
    unitPriceDiscount: number; 
    discountType1: string;
    discount1: number;        
    unitPriceDiscount1: number; 
}